<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN-0NMH0BG7FC5" ignored="0" name="Default test" tests="4" failures="3" timestamp="11 Jul 2017 10:55:56 GMT" time="13.459" errors="0">
  <testcase name="StartApplication" time="3.985" classname="testcases.TestCalculator"/>
  <testcase name="testBaufinanzierung_Antrag_Start" time="0.86" classname="testcases.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Commerzbank Finanzierungsanfrage&amp;gt; but was:&amp;lt;&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Commerzbank Finanzierungsanfrage> but was:<>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at testcases.TestCalculator.testBaufinanzierung_Antrag_Start(TestCalculator.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testBaufinanzierung_Antrag_Start -->
  <testcase name="testBaufinanzierung_Antrag_Zinsen_Check" time="1.687" classname="testcases.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Angaben zu Ihrer Finanzierung&amp;gt; but was:&amp;lt;Zinscheck&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Angaben zu Ihrer Finanzierung> but was:<Zinscheck>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at testcases.TestCalculator.testBaufinanzierung_Antrag_Zinsen_Check(TestCalculator.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testBaufinanzierung_Antrag_Zinsen_Check -->
  <testcase name="testBaufinanzierung_Antrag_Persoenlichen_Daten" time="0.078" classname="testcases.TestCalculator">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Angaben zu Ihrer Finanzierung&amp;gt; but was:&amp;lt;Persönliche Angaben&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Angaben zu Ihrer Finanzierung> but was:<Persönliche Angaben>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at testcases.TestCalculator.testBaufinanzierung_Antrag_Persoenlichen_Daten(TestCalculator.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testBaufinanzierung_Antrag_Persoenlichen_Daten -->
</testsuite> <!-- Default test -->
